### ISSUE TITLE
Update to 1.21.1 stopped neoforge from running.

### ISSUE THREAD

**Issue by WellKnowing** [jaredlll08/MultiLoader-Template#80]
Hello! 
I downloaded this template and wanted to use it. But firstly I wanted to update it to 1.21.1 from 1.21, when I updated, fabric works well, but task runClient for neoforge throws an error...

This is a bit weird, because I can't find anything like "fabric-modId" anywhere.
```
Exception in thread "main" java.lang.IllegalArgumentException: Decoration with key 'fabric-modId' already exists on config neoforge.mixins.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinConfig.decorate(MixinConfig.java:1248)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.mixin.DeferredMixinConfigRegistration.lambda$registerConfigs$1(DeferredMixinConfigRegistration.java:61)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.mixin.DeferredMixinConfigRegistration.registerConfigs(DeferredMixinConfigRegistration.java:54)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.mixin.FMLMixinPlatformAgent.prepare(FMLMixinPlatformAgent.java:24)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:166)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:196)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:200)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:34)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(LaunchPluginHandler.java:106)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:51)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at DevLaunch@1.0.1/net.neoforged.devlaunch.Main.main(Main.java:55)
```

**Comment by WellKnowing** [comment]
Okay, I found that this error appeared when I update from 21.0.60-beta (neoforge version) to 21.0.61-beta. The problem is that I don't see anychanges connected to this...

**Comment by jaredlll08** [comment]
I've updated the template, I didn't run into this issue and I have never seen anything like it.
